import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Featured from '@/components/Featured';
import PizzaList from '@/components/PizzaList';
import axios from 'axios';
import AddButton from '@/components/AddButton';
import { Add } from '@/components/Add';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ productList, isAdmin }) {
  const [close, setClose] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Featured />
        {isAdmin && <AddButton setClose={setClose} isAdmin={isAdmin} />}
        <PizzaList pizzaList={productList} />
        {!close && <Add setClose={setClose} />}
      </main>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || '';
  let isAdmin = false;
  if (myCookie.token === process.env.TOKEN) {
    isAdmin = true;
  }
  const res = await axios.get('http://localhost:3000/api/products');
  return {
    props: {
      productList: res.data,
      isAdmin,
    },
  };
};
